[project]
name = "avocado-salmon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=3.5.0",
    "streamlit>=1.41.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.6",
]
